# Generated by Django 5.2.6 on 2025-11-14 20:45

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('item_offered', models.CharField(default=models.CharField(max_length=100), max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.unique_post_image_path)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Food', 'Food'), ('First-year', 'First-year'), ('Swag', 'Swag'), ('Plants', 'Plants'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50)),
                ('general_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=5, verbose_name='Item Size (General)')),
                ('weight', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], default='M', max_length=5, verbose_name='Item Weight')),
                ('clothing_size', models.CharField(blank=True, choices=[('XS', 'Extra Small (XS)'), ('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)'), ('XXL', 'Double Extra Large (XXL)')], max_length=5, null=True, verbose_name='Clothing Size')),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='Reason for Report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.post')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('Undergraduate Student', 'Undergraduate Student'), ('Graduate Student', 'Graduate Student'), ('Faculty', 'Faculty'), ('Other', 'Other')], default='undergrad', max_length=50)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to=core.models.unique_post_image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sustainability_interests', models.ManyToManyField(blank=True, to='core.sustainabilityinterests')),
                ('trading_interests', models.ManyToManyField(blank=True, to='core.tradinginterests')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Pending', max_length=20)),
                ('item_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_offered_on', to='core.post')),
                ('offered_posts', models.ManyToManyField(related_name='trades_offered_with', to='core.post')),
                ('offerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_made', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('offerer', 'item_requested'), name='unique_pending_trade_per_user_and_post')],
            },
        ),
    ]
