# Generated by Django 5.2.6 on 2025-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
