# Generated by Django 5.2.6 on 2025-11-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_banned',
        ),
    ]
