# Generated by Django 5.2.6 on 2025-11-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_banned_profile_banned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
