# Generated by Django 5.2.6 on 2025-11-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_item_requested_remove_post_otheruser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='comment',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
