# Generated by Django 5.2.6 on 2025-11-02 22:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.unique_post_image_path),
        ),
    ]
