# Generated by Django 5.2.6 on 2025-11-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_logged_in_before',
            field=models.BooleanField(default=False),
        ),
    ]
