# Generated by Django 5.2.6 on 2025-11-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_poster_alter_trade_userone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
