# Generated by Django 5.2.8 on 2025-11-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_has_logged_in_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='undergrad_year',
            field=models.CharField(blank=True, choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Undergraduate Student', 'Undergraduate Student'), ('Graduate Student', 'Graduate Student'), ('Faculty', 'Faculty'), ('Other', 'Other')], default='Undergraduate Student', max_length=50),
        ),
    ]
