# Generated by Django 5.2.6 on 2025-11-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_offered',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
