# Generated by Django 5.2.6 on 2025-11-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_role_sustainability_tags_trading_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school_role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sustainability_interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trading_interests',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Sustainability_Tags',
        ),
        migrations.DeleteModel(
            name='Trading_Tags',
        ),
    ]
