# Generated by Django 5.2.8 on 2025-12-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_undergrad_year_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='undergrad_year',
        ),
    ]
