# Generated by Django 5.2.6 on 2025-11-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_school_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('undergrad', 'Undergraduate Student'), ('grad', 'Graduate Student'), ('faculty', 'Faculty'), ('other', 'Other')], default='undergrad', max_length=20),
        ),
    ]
