# Generated by Django 5.2.8 on 2025-12-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_undergrad_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.TextField(max_length=500, verbose_name='Reason for Report'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
