# Generated by Django 5.2.6 on 2025-11-12 18:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_item_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.unique_post_image_path),
        ),
    ]
