# Generated by Django 5.2.6 on 2025-11-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trade_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='post_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
    ]
