# Generated by Django 5.2.6 on 2025-11-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trade_post_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='available',
            new_name='is_available',
        ),
    ]
