# Generated by Django 5.2.6 on 2025-11-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sustainabilityinterests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='trading_interests',
            field=models.ManyToManyField(blank=True, to='core.tradinginterests'),
        ),
    ]
