# Generated by Django 5.2.6 on 2025-11-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tradinginterests_profile_trading_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Undergraduate Student', 'Undergraduate Student'), ('Graduate Student', 'Graduate Student'), ('Faculty', 'Faculty'), ('Other', 'Other')], default='undergrad', max_length=50),
        ),
    ]
