# Generated by Django 5.2.6 on 2025-11-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interest',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50),
        ),
    ]
