# Generated by Django 5.2.6 on 2025-11-07 22:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.unique_post_image_path),
        ),
    ]
