# Generated by Django 5.2.6 on 2025-11-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_post_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='interest',
            new_name='category',
        ),
    ]
