# Generated by Django 5.2.6 on 2025-11-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_post_category_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clothing_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small (XS)'), ('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)'), ('XXL', 'Double Extra Large (XXL)')], max_length=5, null=True, verbose_name='Clothing Size'),
        ),
        migrations.AddField(
            model_name='post',
            name='general_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=5, verbose_name='Item Size (General)'),
        ),
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], default='M', max_length=5, verbose_name='Item Weight'),
        ),
    ]
