# Generated by Django 5.2.6 on 2025-11-16 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ban', 'Ban User'), ('unban', 'Unban User'), ('delete_post', 'Delete Post'), ('warn_user', 'Warn User'), ('resolve_report', 'Resolve Report'), ('dismiss_report', 'Dismiss Report'), ('system', 'System Action')], max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Optional explanation of the action.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(help_text='The moderator who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_actions', to=settings.AUTH_USER_MODEL)),
                ('target_post', models.ForeignKey(blank=True, help_text='Post affected by moderation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_actions', to='core.post')),
                ('target_report', models.ForeignKey(blank=True, help_text='Report associated with this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_actions', to='core.report')),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_taken_against', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_written', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notes', to='core.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='core.report')),
            ],
        ),
    ]
