name: Django Tests

on:
  push:
    branches: ["*"]

jobs:
  django_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DJANGO_SECRET_KEY: "testsecret"
      DEBUG: "True"
      DATABASE_URL: "postgres://postgres:postgres@127.0.0.1:5432/test_db"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check running containers
        run: docker ps -a

      - name: Wait for Postgres
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run migrations
        run: python manage.py migrate

      - name: Run Django tests
        run: python manage.py test
